info:
  name: CumulatedvaluesAsOfByAccount
  type: http
  seq: 15
http:
  method: GET
  url: '{{Portfolio}}/public/api/v1/accounts/:accountId/portfolio/cumulatedvalues/asof'
  params:
  - name: accountId
    value: ''
    type: path
  - name: requestedCurrency
    value: ''
    type: query
    disabled: true
  - name: portfolioDate
    value: ''
    type: query
    disabled: true
  body: null
  auth: inherit
settings:
  encodeUrl: true
  timeout: 0
  followRedirects: true
  maxRedirects: 5
docs: '# Summary

  Retrieves the cumulated portfolio values for a specific account as of a given date.


  ## Description

  `min ref 2025-02 (90.48)`


  ## Parameters


  - **accountId** (path) : The unique identifier of the account for which the portfolio
  values are requested.

  - **requestedCurrency** (query) : The currency in which the portfolio will be returned.
  The list of supported currencies follows the International Standard for currency
  codes (ISO 4217).

  - **portfolioDate** (query) : The date to use for the portfolio calculation'
